[package]
name = "chiika_runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
rand = "0.8.5"
rand_chacha = "0.3.0"
#bdwgc-alloc = { version = "0.6.5", default-features=false, features = ["cmake"] }
